### ISSUE TITLE
443 error when using Jira in Alfred

### ISSUE THREAD

**Issue by kpreston1** [titouanmathis/alfred-jira-search#1]
I am getting a 443 error when running the basic Search Jira Issues command. Here is the error that I am getting. Has anyone else seen this issue, or found a way to resolve it?

```
RequestError: getaddrinfo ENOTFOUND .atlassian.net .atlassian.net:443
    at ClientRequest.request.once.error (/Users/username/.npm-global/lib/node_modules/alfred-jira-search/node_modules/got/source/request-as-event-emitter.js:178:14)
    at ClientRequest.origin.emit.args (/Users/username/.npm-global/lib/node_modules/alfred-jira-search/node_modules/@szmarczak/http-timer/source/index.js:37:11)
```

-
Jira 1.0.2
Alfred 4.0.9
darwin 19.5.0

**Comment by titouanmathis** [comment]
Hi @kpreston1, did you configure the workflow variables `JIRA_ORG`, `JIRA_USERNAME` and `JIRA_TOKEN`? 
The error makes me think the workflow is at least missing the `JIRA_ORG` one. Let me know if this helps you!

You can check the [readme](https://github.com/titouanmathis/alfred-jira-search#configuration) to see what these variables should be.

**Comment by titouanmathis** [comment]
Closing this for now, feel free to reopen with more informations if the problem persists.
